import { test } from 'node:test'
import assert from 'node:assert/strict'

import { commentStyle, withHeader } from '../src/header.js'

const meta = { repository: 'webitel/reusable-configs', source: 'golang/workflows/pull-request.yml.njk' }
const HASH_HEADER = [
    '# Code generated by file-sync from webitel/reusable-configs. DO NOT EDIT.',
    '# Source: golang/workflows/pull-request.yml.njk',
    '# Edit the source instead; local changes are overwritten on the next sync.',
    ''
].join('\n')

test('commentStyle picks the comment syntax by file name', () => {
    for (const file of [ 'a.yml', 'a.yaml', 'deploy/postinst.sh', 'tool.py', 'pyproject.toml', 'setup.cfg', '.gitignore', '.dockerignore', '.gitattributes', '.editorconfig', 'Makefile', 'Dockerfile', 'build/Dockerfile.dev', '.env.example' ]) {
        assert.deepEqual(commentStyle(file), { start: '#' }, file)
    }
    for (const file of [ 'main.go', 'index.js', 'index.mjs', 'app.ts', 'tsconfig.jsonc', '.vscode/settings.json' ]) {
        assert.deepEqual(commentStyle(file), { start: '//' }, file)
    }
    for (const file of [ '.idea/codeStyles/Project.xml', 'module.iml', 'index.html' ]) {
        assert.deepEqual(commentStyle(file), { start: '<!--', end: '-->' }, file)
    }
    for (const file of [ 'package.json', 'README.md', 'logo.png', 'LICENSE' ]) {
        assert.equal(commentStyle(file), undefined, file)
    }
})

test('withHeader prepends the header to a YAML file, before a document start', () => {
    assert.equal(withHeader('---\nname: x\n', { ...meta, file: 'a.yml' }), `${ HASH_HEADER }\n---\nname: x\n`)
})

test('withHeader keeps a shebang on the first line', () => {
    assert.equal(withHeader('#!/bin/sh\nset -e\n', { ...meta, file: 'postinst.sh' }), `#!/bin/sh\n${ HASH_HEADER }\nset -e\n`)
})

test('withHeader keeps the XML declaration on the first line', () => {
    const content = '<?xml version="1.0" encoding="UTF-8"?>\n<project/>\n'
    assert.equal(withHeader(content, { ...meta, file: 'a.xml' }), [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!-- Code generated by file-sync from webitel/reusable-configs. DO NOT EDIT. -->',
        '<!-- Source: golang/workflows/pull-request.yml.njk -->',
        '<!-- Edit the source instead; local changes are overwritten on the next sync. -->',
        '',
        '<project/>',
        ''
    ].join('\n'))
})

test('withHeader writes the Go generated-code marker for Go files', () => {
    assert.match(withHeader('package main\n', { ...meta, file: 'main.go' }), /^\/\/ Code generated by file-sync from webitel\/reusable-configs\. DO NOT EDIT\.\n/)
})

test('withHeader replaces an existing header instead of adding a second one', () => {
    const once = withHeader('name: x\n', { ...meta, file: 'a.yml' })
    const moved = withHeader(once, { ...meta, source: 'common/a.yml', file: 'a.yml' })

    assert.equal(withHeader(once, { ...meta, file: 'a.yml' }), once)
    const xml = withHeader('<?xml version="1.0"?>\n<project/>\n', { ...meta, file: 'a.xml' })
    assert.equal(withHeader(xml, { ...meta, file: 'a.xml' }), xml)
    assert.equal(moved.match(/Code generated by file-sync/g).length, 1)
    assert.match(moved, /# Source: common\/a\.yml\n/)
})

test('withHeader leaves files without a comment syntax and binary files unchanged', () => {
    assert.equal(withHeader('{"a": 1}\n', { ...meta, file: 'package.json' }), '{"a": 1}\n')
    assert.equal(withHeader('a\0b', { ...meta, file: 'a.yml' }), 'a\0b')
})
