import { test } from 'node:test'
import assert from 'node:assert/strict'
import * as yaml from 'js-yaml'

import { createSandbox } from './support/harness.js'
import { sha256 } from '../src/manifest.js'

const TARGET = 'webitel/target'
const CONFIG = `
webitel/target:
  - source: golang/a.yml
    dest: a.yml
  - source: golang/pr.yml.njk
    dest: pr.yml
    template:
      name: cases
  - source: golang/.idea/
    dest: .idea/
    header: false
`
const FILES = {
    '.github/sync.yml': CONFIG,
    'golang/a.yml': 'a: 1\n',
    'golang/pr.yml.njk': 'name: {{ name }}\n',
    'golang/.idea/misc.xml': '<project/>\n'
}

test('FILE_HEADER marks synced files with their source, except entries with header: false', async () => {
    const sandbox = await createSandbox()
    await sandbox.createTarget(TARGET)
    await sandbox.commitSource('initial', FILES)

    const result = await sandbox.runAction({ inputs: { SKIP_PR: true, FILE_HEADER: true } })

    assert.equal(result.failed, false, result.output)
    assert.equal(sandbox.readTarget(TARGET, 'main', 'a.yml'), [
        '# Code generated by file-sync from webitel/source. DO NOT EDIT.',
        '# Source: golang/a.yml',
        '# Edit the source instead; local changes are overwritten on the next sync.',
        '',
        'a: 1'
    ].join('\n'))
    assert.match(sandbox.readTarget(TARGET, 'main', 'pr.yml'), /^# Code generated .*\n# Source: golang\/pr\.yml\.njk\n[\s\S]*\nname: cases$/)
    assert.equal(sandbox.readTarget(TARGET, 'main', '.idea/misc.xml'), '<project/>')
})

test('the manifest hashes the files with their header, and a re-run changes nothing', async () => {
    const sandbox = await createSandbox()
    await sandbox.createTarget(TARGET)
    await sandbox.commitSource('initial', FILES)
    await sandbox.runAction({ inputs: { SKIP_PR: true, FILE_HEADER: true } })
    const head = sandbox.targetLog(TARGET, 'main', '%H')

    const result = await sandbox.runAction({ inputs: { SKIP_PR: true, FILE_HEADER: true } })

    assert.equal(result.failed, false, result.output)
    assert.equal(sandbox.targetLog(TARGET, 'main', '%H'), head)
    const manifest = yaml.load(sandbox.readTarget(TARGET, 'main', '.github/file-sync/sync.yml'))
    assert.equal(manifest.files['a.yml'].sha256, sha256(sandbox.readTarget(TARGET, 'main', 'a.yml') + '\n'))
})

test('files get no header without FILE_HEADER', async () => {
    const sandbox = await createSandbox()
    await sandbox.createTarget(TARGET)
    await sandbox.commitSource('initial', FILES)

    await sandbox.runAction({ inputs: { SKIP_PR: true } })

    assert.equal(sandbox.readTarget(TARGET, 'main', 'a.yml'), 'a: 1')
})
