import { test } from 'node:test'
import assert from 'node:assert/strict'
import fs from 'fs-extra'
import * as os from 'os'
import * as path from 'path'

import {
    manifestName,
    manifestPath,
    sha256,
    serializeManifest,
    parseManifest,
    readManifest,
    sameFiles,
    findOwnershipConflicts,
    findDrift
} from '../src/manifest.js'

test('manifestName derives the stream name from the config path', () => {
    assert.equal(manifestName('golang/sync.yml'), 'golang-sync')
    assert.equal(manifestName('golang/sync-static.yaml'), 'golang-sync-static')
    assert.equal(manifestName('./python/sync.yml'), 'python-sync')
})

test('manifestName drops the .github directory of the default config path', () => {
    assert.equal(manifestName('.github/sync.yml'), 'sync')
})

test('manifestPath places the manifest under .github/file-sync', () => {
    assert.equal(manifestPath('golang-sync'), '.github/file-sync/golang-sync.yml')
})

test('sha256 returns the hex digest of the content', () => {
    assert.equal(sha256('abc'), 'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad')
})

const manifest = {
    name: 'golang-sync',
    repository: 'webitel/reusable-configs',
    config: 'golang/sync.yml',
    sha: '1a2b3c4d',
    files: {
        'b.yml': { source: 'golang/b.yml', sha256: 'bb' },
        'a.yml': { source: 'golang/a.yml.njk', sha256: 'aa' }
    }
}

test('serializeManifest writes a generated-file header and sorted files', () => {
    const text = serializeManifest(manifest)

    assert.match(text, /^# Code generated by file-sync\. DO NOT EDIT\.\n# Files managed by the "golang-sync" stream of webitel\/reusable-configs\.\n/)
    assert.ok(text.indexOf('a.yml:') < text.indexOf('b.yml:'))
})

test('parseManifest reads what serializeManifest writes', () => {
    assert.deepEqual(parseManifest(serializeManifest(manifest)), {
        version: 1,
        source: { repository: 'webitel/reusable-configs', config: 'golang/sync.yml', sha: '1a2b3c4d' },
        files: manifest.files
    })
})

test('parseManifest rejects an unknown version', () => {
    assert.throws(() => parseManifest('version: 2\nfiles: {}\n'), /unsupported manifest version 2/)
})

test('readManifest returns undefined when the file does not exist', async () => {
    assert.equal(await readManifest(path.join(os.tmpdir(), 'file-sync-missing', 'x.yml')), undefined)
})

test('sameFiles compares sources and hashes regardless of key order', () => {
    const reordered = { 'a.yml': manifest.files['a.yml'], 'b.yml': manifest.files['b.yml'] }
    assert.equal(sameFiles(manifest.files, reordered), true)
    assert.equal(sameFiles(manifest.files, { ...reordered, 'b.yml': { source: 'golang/b.yml', sha256: 'cc' } }), false)
    assert.equal(sameFiles(manifest.files, { 'a.yml': manifest.files['a.yml'] }), false)
    assert.equal(sameFiles(undefined, {}), true)
})

test('findOwnershipConflicts reports files listed in manifests of other streams', async () => {
    const repo = await fs.mkdtemp(path.join(os.tmpdir(), 'file-sync-test-'))
    await fs.outputFile(path.join(repo, manifestPath('golang-sync-static')), serializeManifest({
        ...manifest, name: 'golang-sync-static', files: { 'a.yml': { source: 'x', sha256: 'y' } }
    }))
    await fs.outputFile(path.join(repo, manifestPath('golang-sync')), serializeManifest(manifest))

    const conflicts = await findOwnershipConflicts(repo, 'golang-sync', [ 'a.yml', 'b.yml' ])

    assert.deepEqual(conflicts, [ { dest: 'a.yml', stream: 'golang-sync-static' } ])
})

test('findDrift lists managed files whose content differs from the manifest or that were deleted', async () => {
    const repo = await fs.mkdtemp(path.join(os.tmpdir(), 'file-sync-test-'))
    await fs.outputFile(path.join(repo, 'same.yml'), 'same')
    await fs.outputFile(path.join(repo, 'edited.yml'), 'local')

    const drift = await findDrift(repo, { files: {
        'same.yml': { source: 's', sha256: sha256('same') },
        'edited.yml': { source: 's', sha256: sha256('synced') },
        'gone.yml': { source: 's', sha256: sha256('synced') }
    } })

    assert.deepEqual(drift, [ { dest: 'edited.yml', deleted: false }, { dest: 'gone.yml', deleted: true } ])
})
