outputs:
  version:
    value: ${{ steps.check.outputs.version }}
    description: Latest release branch

runs:
  using: composite
  steps:
    - name: For each git ref
      id: check
      shell: bash
      run: |
        set +o pipefail
        latest_branch=$(git ls-remote --heads origin "v*" \
          | awk '{print $2}' \
          | sed 's|refs/heads/||' \
          | grep -E '^v[0-9]+\.[0-9]+$' \
          | sort -rV \
          | head -n1 || true)
        set -o pipefail

        echo "Latest release branch: $latest_branch"
        echo "version=$latest_branch" >> "$GITHUB_OUTPUT"
