name: Backport
description: Backports a commit to the selected release branches

inputs:
  token:
    required: true
    description: GitHub token with access to all necessary repositories

  labels-to-add:
    required: true
    description: Comma delimited list of labels to add to the backport PRs

  binary-release-tag:
    required: false
    default: "dev"
    description: ""

  path:
    required: false
    default: "."
    description: ""

  pr-label:
    required: false
    description: If specified, the backport will only be created for this label

  pr-number:
    required: false
    description: The number of the PR to backport

  repo-owner:
    required: false
    description: The owner of the repository the PR is in

  repo-name:
    required: false
    description: The name of the repository the PR is in

runs:
  using: composite
  steps:
    - shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        RELEASE_TAG: ${{ inputs.binary-release-tag }}
        INPUT_LABELS_TO_ADD: ${{ inputs.labels-to-add }}
        DIR: ${{ inputs.path }}
        PR_LABEL: ${{ inputs.pr-label }}
        PR_NUMBER: ${{ inputs.pr-number }}
        REPO_OWNER: ${{ inputs.repo-owner }}
        REPO_NAME: ${{ inputs.repo-name }}

      run: |
        set -e
        # Download the action from the store
        curl --fail -L -o /tmp/backport https://github.com/webitel/reusable-workflows/releases/download/${RELEASE_TAG}/backport
        chmod +x /tmp/backport
        cd $DIR
        # Execute action
        /tmp/backport