import * as path from 'path'

const HASH = { start: '#' }
const SLASH = { start: '//' }
const XML = { start: '<!--', end: '-->' }

const BY_EXTENSION = {
    '.yml': HASH, '.yaml': HASH, '.sh': HASH, '.bash': HASH, '.py': HASH, '.toml': HASH,
    '.ini': HASH, '.cfg': HASH, '.conf': HASH, '.properties': HASH,
    '.go': SLASH, '.js': SLASH, '.mjs': SLASH, '.cjs': SLASH, '.ts': SLASH, '.jsonc': SLASH,
    '.xml': XML, '.iml': XML, '.html': XML
}

const BY_NAME = {
    'Makefile': HASH, 'Dockerfile': HASH,
    '.gitignore': HASH, '.dockerignore': HASH, '.gitattributes': HASH, '.editorconfig': HASH
}

const MARKER = 'Code generated by file-sync'

// Comment syntax for a file, or undefined when its format has no comments (e.g. JSON, Markdown front matter)
export function commentStyle(file) {
    const name = path.basename(file)
    if (BY_NAME[name]) return BY_NAME[name]
    if (name.startsWith('Dockerfile.') || name.startsWith('.env')) return HASH
    // VS Code reads its settings as JSON with comments
    if (path.extname(name) === '.json' && path.dirname(file).split(path.sep).includes('.vscode')) return SLASH

    return BY_EXTENSION[path.extname(name)]
}

/**
 * Puts the generated-file header on top of content (after a shebang or an XML declaration).
 * An existing file-sync header is replaced, so the result is stable across syncs.
 */
export function withHeader(content, { file, repository, source }) {
    const style = commentStyle(file)
    if (!style || content.includes('\0')) return content

    const comment = (text) => style.end ? `${ style.start } ${ text } ${ style.end }` : `${ style.start } ${ text }`
    const header = [
        comment(`${ MARKER } from ${ repository }. DO NOT EDIT.`),
        comment(`Source: ${ source }`),
        comment('Edit the source instead; local changes are overwritten on the next sync.'),
        ''
    ]

    const lines = content.split('\n')
    const at = /^(#!|<\?xml)/.test(lines[0]) ? 1 : 0

    // Drop a previous header: its three comment lines and the blank line after them
    if (lines[at]?.startsWith(`${ style.start } ${ MARKER }`)) lines.splice(at, header.length)

    lines.splice(at, 0, ...header)
    return lines.join('\n')
}
