import { createHash } from 'crypto'
import fs from 'fs-extra'
import * as yaml from 'js-yaml'
import * as path from 'path'

const MANIFEST_DIR = '.github/file-sync'
const MANIFEST_VERSION = 1

// Derives the stream name from the sync config path: golang/sync-static.yml -> golang-sync-static
export function manifestName(configPath) {
    return path.posix.normalize(configPath)
        .replace(/^\.github\//, '')
        .replace(/\.ya?ml$/, '')
        .replace(/\//g, '-')
}

export function manifestPath(name) {
    return `${ MANIFEST_DIR }/${ name }.yml`
}

export function sha256(content) {
    return createHash('sha256').update(content).digest('hex')
}

export function serializeManifest({ name, repository, config, sha, files }) {
    const sorted = Object.fromEntries(Object.keys(files).sort().map((dest) => [ dest, files[dest] ]))
    const body = yaml.dump({
        version: MANIFEST_VERSION,
        source: { repository, config, sha },
        files: sorted
    }, { lineWidth: -1, noRefs: true })

    return `# Code generated by file-sync. DO NOT EDIT.\n# Files managed by the "${ name }" stream of ${ repository }.\n${ body }`
}

export function parseManifest(text) {
    const manifest = yaml.load(text)
    if (manifest?.version !== MANIFEST_VERSION) {
        throw new Error(`unsupported manifest version ${ manifest?.version }`)
    }

    return {
        version: manifest.version,
        source: manifest.source || {},
        files: manifest.files || {}
    }
}

export async function readManifest(file) {
    if (!await fs.pathExists(file)) return undefined

    return parseManifest(await fs.readFile(file, 'utf8'))
}

export function sameFiles(a = {}, b = {}) {
    const keys = Object.keys(a)
    if (keys.length !== Object.keys(b).length) return false

    return keys.every((dest) => b[dest] !== undefined && a[dest].source === b[dest].source && a[dest].sha256 === b[dest].sha256)
}

// Lists dest files that a manifest of another stream in the same repository already owns.
export async function findOwnershipConflicts(repoDir, name, destFiles) {
    const dir = path.join(repoDir, MANIFEST_DIR)
    if (!await fs.pathExists(dir)) return []

    const conflicts = []
    for (const entry of (await fs.readdir(dir)).sort()) {
        const stream = entry.replace(/\.yml$/, '')
        if (stream === entry || stream === name) continue

        const other = await readManifest(path.join(dir, entry))
        for (const dest of destFiles) {
            if (other.files[dest] !== undefined) conflicts.push({ dest, stream })
        }
    }

    return conflicts
}

// Lists managed files edited or deleted in the target repository since the manifest was written, as [{ dest, deleted }]
export async function findDrift(repoDir, manifest) {
    const drift = []
    for (const dest of Object.keys(manifest.files).sort()) {
        const file = path.join(repoDir, dest)
        if (!await fs.pathExists(file)) {
            drift.push({ dest, deleted: true })
        } else if (sha256(await fs.readFile(file)) !== manifest.files[dest].sha256) {
            drift.push({ dest, deleted: false })
        }
    }
    return drift
}
