# Runs the actual backport after being triggered by the backport-trigger.yml workflow.
name: Backport (workflow)
run-name: "Backport for ${{ github.event.workflow_run.head_branch }} #${{ github.event.workflow_run.run_number }}"

on:
  workflow_call:

jobs:
  perform:
    name: Perform backport
    runs-on: [ arc-runner-set ]
    permissions:
      id-token: write
      actions: read

    steps:
      - name: Download PR info artifact
        uses: actions/download-artifact@v4
        id: download-pr-info
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          name: pr_info

      - name: Get PR info
        id: pr-info
        env:
          PR_INFO_FILE: ${{ steps.download-pr-info.outputs.download-path }}/pr_info.json

        # jq-magic to convert the JSON object into a list of key=value pairs for $GITHUB_OUTPUT
        run:
          jq -r 'to_entries[] | select(.value | type != "object") | "\(.key)=\(.value)"' "$PR_INFO_FILE" >> "$GITHUB_OUTPUT"

      - name: Print PR info
        env:
          PR_ACTION: ${{ steps.pr-info.outputs.action }}
          PR_LABEL: ${{ steps.pr-info.outputs.label }}
          PR_NUMBER: ${{ steps.pr-info.outputs.pr_number }}

        run: |
          echo "PR action: $PR_ACTION"
          echo "PR label: $PR_LABEL"
          echo "PR number: $PR_NUMBER"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 2
          fetch-tags: false
          token: ${{ steps.generate_token.outputs.token }}
          persist-credentials: true

      - name: Configure git user
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local --add --bool push.autoSetupRemote true

      - name: Run backport
        uses: webitel/reusable-workflows/actions/backport@backport-v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          # If triggered by being labelled, only backport that label.
          # Otherwise, the action will backport all labels.
          pr_label: ${{ steps.pr-info.outputs.action == 'labeled' && steps.pr-info.outputs.label || '' }}
          pr_number: ${{ steps.pr-info.outputs.pr_number }}
          repo_owner: ${{ github.repository_owner }}
          repo_name: ${{ github.event.repository.name }}
          labelsToAdd: "backport"