# We need secrets to backport, but they're not available for actions ran by forks.
# So this workflow is used as a 'trigger', which the backport-workflow.yml will with
# via workflow_run
name: Backport (trigger)

on:
  workflow_call:

jobs:
  trigger:
    name: Trigger
    runs-on: [ arc-runner-set ]
    steps:
      - name: Logs
        run: |
          echo "Triggering workflow"
          echo "See https://github.com/${{ github.repository }}/actions/workflows/workflow_run.yml for progress"

      # Create a JSON artifact with details of this PR to pass to the backport workflow.
      # The { action: 'labelled', label: 'backport v25.08' } can only be determined from this event payload,
      # and is needed to do a backport after a PR has been merged
      #
      # Important that we don't run *anything* from the PR which could modify the backport_data.json file
      - name: Create action data
        run: |
          jq '{
            action: .action,
            label: .label.name,
            pr_number: .number,
          }' "$GITHUB_EVENT_PATH" > /tmp/pr_info.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr_info
          path: /tmp/pr_info.json
          retention-days: 1
