name: Deploy

on:
  workflow_call:
    secrets:
      DEPLOYMENTS_SSH_USER: { required: true }
      DEPLOYMENTS_SSH_PRIVATE_KEY: { required: true }
      DEPLOYMENTS_SSH_HOST_DEVELOPMENT: { required: true }
      DEPLOYMENTS_SSH_HOST_TESTING: { required: true }
      DEPLOYMENTS_SSH_HOST_STAGING: { required: true }
      DEB_AWS_ACCESS_KEY_ID: { required: true }
      DEB_AWS_SECRET_ACCESS_KEY: { required: true }
      REPO_SIGNING_KEY: { required: true }
      REPO_SIGNING_KEY_PASSPHRASE: { required: true }
      GH_PAT: { required: false }

    inputs:
      triggered-branch:
        type: string
        required: false
        default: ${{ github.ref_name }}

      tag:
        type: string
        required: false
        description: Package version to create tag.

      tag-target-commitish:
        type: string
        required: false
        default: ${{ github.sha }}

      repository-environment:
        type: string
        required: false
        default: acceptance
        description: Linked environment for upload build to repository (eg. acceptance, v25.04-releases, ...).

      deb-package-pattern:
        type: string
        required: true
        description: A path pattern to artifact, that should be uploaded to environments and installed.

      deb-component:
        type: string
        required: false
        default: dev
        description: Component of the APT repository.

      deb-codename:
        type: string
        required: true
        description: Nickname used for specific Debian releases.

      deb-aws-bucket-name:
        type: string
        required: true

      deb-aws-bucket-region:
        type: string
        required: true

      artifact-repository:
        type: string
        required: false
        description: |
          The repository owner and the repository name joined together by "/".
          If artifact-github-token is specified, this is the repository that artifacts will be downloaded from.

      artifact-actions-run-id:
        type: string
        required: false
        description: |
          The id of the workflow run where the desired download artifact was uploaded from.
          If artifact-github-token is specified, this is the run that artifacts will be downloaded from.

jobs:
  development:
    name: Development
    runs-on: [ arc-runner-set ]
    if: inputs.repository-environment == 'acceptance'
    environment: development
    steps:
      - name: Deploy
        uses: webitel/reusable-workflows/actions/deploy-action@main
        with:
          source: ${{ inputs.deb-package-pattern }}
          host: ${{ secrets.DEPLOYMENTS_SSH_HOST_DEVELOPMENT }}
          user: ${{ secrets.DEPLOYMENTS_SSH_USER }}
          private-key: ${{ secrets.DEPLOYMENTS_SSH_PRIVATE_KEY }}
          artifact-repository: ${{ inputs.artifact-repository }}
          artifact-actions-run-id: ${{ inputs.artifact-actions-run-id }}
          artifact-github-token: ${{ secrets.GH_PAT }}

  testing:
    name: Testing
    runs-on: [ arc-runner-set ]
    needs: [ development ]
    if: inputs.repository-environment == 'acceptance'
    environment: testing
    steps:
      - name: Deploy
        uses: webitel/reusable-workflows/actions/deploy-action@main
        with:
          source: ${{ inputs.deb-package-pattern }}
          host: ${{ secrets.DEPLOYMENTS_SSH_HOST_TESTING }}
          user: ${{ secrets.DEPLOYMENTS_SSH_USER }}
          private-key: ${{ secrets.DEPLOYMENTS_SSH_PRIVATE_KEY }}
          artifact-repository: ${{ inputs.artifact-repository }}
          artifact-actions-run-id: ${{ inputs.artifact-actions-run-id }}
          artifact-github-token: ${{ secrets.GH_PAT }}

  check-latest:
    name: Check latest release
    runs-on: [ arc-runner-set ]
    if: inputs.repository-environment != 'acceptance'
    outputs:
      latest: ${{ steps.check.outputs.latest }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history so we can list branches

      - name: For each git ref
        id: check
        run: |
          current_branch="${{ inputs.triggered-branch }}"
          echo "Current branch: $current_branch"

          latest_branch=$(git ls-remote --heads origin 'v*.*' \
            | grep -E 'refs/heads/v[0-9]+\.[0-9]+$' \
            | awk '{print $2}' \
            | sed 's|refs/heads/||' \
            | sort -rV \
            | head -n1)

          echo "Latest release branch: $latest_branch"
          if [[ "$current_branch" == "$latest_branch" ]]; then
            echo "latest=true" >> "$GITHUB_OUTPUT"
          fi

  staging:
    name: Staging
    needs: [ check-latest ]
    if: inputs.repository-environment != 'acceptance' && needs.check-latest.outputs.latest == 'true'
    runs-on: [ arc-runner-set ]
    environment: staging
    steps:
      - name: Deploy
        uses: webitel/reusable-workflows/actions/deploy-action@main
        with:
          source: ${{ inputs.deb-package-pattern }}
          host: ${{ secrets.DEPLOYMENTS_SSH_HOST_STAGING }}
          user: ${{ secrets.DEPLOYMENTS_SSH_USER }}
          private-key: ${{ secrets.DEPLOYMENTS_SSH_PRIVATE_KEY }}
          artifact-repository: ${{ inputs.artifact-repository }}
          artifact-actions-run-id: ${{ inputs.artifact-actions-run-id }}
          artifact-github-token: ${{ secrets.GH_PAT }}

  repository:
    name: Publish .deb package
    runs-on: [ arc-runner-set ]
    needs: [ testing, check-latest, staging ]

    # Run even if previous jobs fail or are cancelled, but
    # do not run if the workflow was cancelled.
    # Case 1: Development deployment (acceptance environment)
    # Case 2: Latest release deployment (non-acceptance environment)
    # Case 3: Other release deployment (non-acceptance environment and not latest release)
    if: |
      always() && !cancelled() &&
      ((inputs.repository-environment == 'acceptance' && needs.testing.result == 'success') ||
        (inputs.repository-environment != 'acceptance' && needs.check-latest.outputs.latest == 'true' && needs.staging.result == 'success') ||
        (inputs.repository-environment != 'acceptance' && needs.check-latest.outputs.latest != 'true'))

    environment: ${{ inputs.repository-environment }}
    steps:
      - name: Publish build
        uses: webitel/reusable-workflows/actions/deb-s3-upload-action@main
        with:
          source: ${{ inputs.deb-package-pattern }}
          component: ${{ inputs.component }}
          codename: ${{ inputs.deb-codename }}
          aws-bucket-name: ${{ inputs.deb-aws-bucket-name }}
          aws-bucket-region: ${{ inputs.deb-aws-bucket-region }}
          aws-secret-id: ${{ secrets.DEB_AWS_ACCESS_KEY_ID }}
          aws-secret-key: ${{ secrets.DEB_AWS_SECRET_ACCESS_KEY }}
          gpg-private-key: ${{ secrets.REPO_SIGNING_KEY }}
          gpg-passphrase: ${{ secrets.REPO_SIGNING_KEY_PASSPHRASE }}
          artifact-repository: ${{ inputs.artifact-repository }}
          artifact-actions-run-id: ${{ inputs.artifact-actions-run-id }}
          artifact-github-token: ${{ secrets.GH_PAT }}

  release:
    name: Release assets
    needs: [ check-latest, staging ]
    runs-on: [ arc-runner-set ]
    if: |
      always() && !cancelled() && inputs.repository-environment != 'acceptance' && inputs.tag != '' &&
      ((inputs.repository-environment != 'acceptance' && needs.check-latest.outputs.latest == 'true' && needs.staging.result == 'success') ||
        (inputs.repository-environment != 'acceptance' && needs.check-latest.outputs.latest != 'true'))

    permissions: { contents: write }
    steps:
      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: build-packages
          path: dist
          repository: ${{ inputs.artifact-repository }}
          run-id: ${{ inputs.artifact-actions-run-id }}
          github-token: ${{ secrets.GH_PAT }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ inputs.tag }}
          tag_name: ${{ inputs.tag }}
          target_commitish: ${{ inputs.tag-target-commitish }}
          make_latest: ${{ needs.check-latest.outputs.latest }}
          generate_release_notes: true
          draft: false
          files: dist/*