name: Checks

on:
  pull_request:
    branches: [ main ]

  workflow_call:
    inputs:
      wire:
        description: Download wire generated code
        required: false
        default: false
        type: boolean

jobs:
  lint:
    name: Lint code
    runs-on: [ arc-runner-set ]
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Checkout repository
        env:
          action_repo: ${{ github.action_repository }}
          action_ref: ${{ github.action_ref }}
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: ${{ env.action_repo }}
          ref: ${{ env.action_ref }}
          path: _shared-workflows-download-generated
          persist-credentials: false

      - name: Download generated code
        uses: ./_shared-workflows-download-generated/actions/download-generated
        with:
          wire: ${{ inputs.wire }}

      - name: Cleanup checkout directory
        if: ${{ !cancelled() }}
        run: |
          # Check that the directory looks OK before removing it
          if ! [ -d "_shared-workflows-download-generated/.git" ]; then
            echo "::warning Not removing shared workflows directory: doesn't look like a git repository"
          exit 0
          fi
          
          rm -rf _shared-workflows-download-generated

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6.5.2
        with:
          install-mode: none
          problem-matchers: true
          skip-cache: true

  govulncheck:
    name: Vulnerabilities
    runs-on: [ arc-runner-set ]
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Checkout repository
        env:
          action_repo: ${{ github.action_repository }}
          action_ref: ${{ github.action_ref }}
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: ${{ env.action_repo }}
          ref: ${{ env.action_ref }}
          path: _shared-workflows-download-generated
          persist-credentials: false

      - name: Download generated code
        uses: ./_shared-workflows-download-generated/actions/download-generated
        with:
          wire: ${{ inputs.wire }}

      - name: Cleanup checkout directory
        if: ${{ !cancelled() }}
        run: |
          # Check that the directory looks OK before removing it
          if ! [ -d "_shared-workflows-download-generated/.git" ]; then
            echo "::warning Not removing shared workflows directory: doesn't look like a git repository"
          exit 0
          fi
          
          rm -rf _shared-workflows-download-generated

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck and save to file
        run: govulncheck -C . -format sarif ./... > report.sarif

      - name: Upload to code-scanning
        uses: github/codeql-action/upload-sarif@28deaeda66b76a05916b6923827895f2b14ab387 # v3.28.16
        with:
          sarif_file: report.sarif

  test:
    name: Unit testing
    runs-on: [ arc-runner-set ]
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Checkout repository
        env:
          action_repo: ${{ github.action_repository }}
          action_ref: ${{ github.action_ref }}
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: ${{ env.action_repo }}
          ref: ${{ env.action_ref }}
          path: _shared-workflows-download-generated
          persist-credentials: false

      - name: Download generated code
        uses: ./_shared-workflows-download-generated/actions/download-generated
        with:
          wire: ${{ inputs.wire }}

      - name: Cleanup checkout directory
        if: ${{ !cancelled() }}
        run: |
          # Check that the directory looks OK before removing it
          if ! [ -d "_shared-workflows-download-generated/.git" ]; then
            echo "::warning Not removing shared workflows directory: doesn't look like a git repository"
          exit 0
          fi
          
          rm -rf _shared-workflows-download-generated

      - name: Run all tests
        run: go test -short -v ./... | go run github.com/jstemmer/go-junit-report@latest -set-exit-code > report.xml

      - name: Test Summary
        if: always()
        uses: test-summary/action@v2.4
        with:
          paths: report.xml
