name: Prepare

on:
  workflow_call:
    inputs:
      development-branch:
        type: string
        required: false
        default: main
        description: Name of the development branch

      triggered-branch:
        type: string
        required: false
        default: ${{ github.ref_name }}
        description: Name of the triggered branch

      build-number:
        type: string
        required: false
        default: ${{ github.run_number }}
        description: Build number

      only-dependencies:
        type: string
        required: false
        default: false

      generated-code-path:
        type: string
        required: false
        default: ''

    outputs:
      component:
        value: ${{ jobs.version.outputs.component }}
        description: Extracted component

      version:
        value: ${{ jobs.version.outputs.version }}
        description: Extracted version

      version-build:
        value: ${{ jobs.version.outputs.version-build }}

jobs:
  version:
    name: Version
    if: inputs.only-dependencies != 'true'
    uses: webitel/reusable-workflows/.github/workflows/_version.yml@main
    with:
      development-branch: ${{ inputs.development-branch }}
      triggered-branch: ${{ inputs.triggered-branch }}
      build-number: ${{ inputs.build-number }}

  dependencies:
    name: Dependencies
    runs-on: [ arc-runner-set ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Download dependencies
        run: go mod download

  generated:
    name: Code
    runs-on: [ arc-runner-set ]
    if: inputs.generated-code-path != ''
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Generate code
        run: go generate ./...

      - name: Upload generated code
        uses: actions/upload-artifact@v4
        with:
          name: generated-code
          compression-level: 9
          path: |
            dummy-file-to-keep-directory-structure.txt
            ${{ inputs.generated-code-path }}
