name: Prepare

on:
  workflow_call:
    inputs:
      development-branch:
        type: string
        required: false
        default: main
        description: Name of the development branch

      triggered-branch:
        type: string
        required: false
        default: ${{ github.ref_name }}
        description: Name of the triggered branch

      build-number:
        type: string
        required: false
        default: ${{ github.run_number }}
        description: Build number

      only-dependencies:
        type: boolean
        required: false
        default: false

      generate-code:
        type: boolean
        required: false
        default: false
        description: Should generate code in workflow

      wire:
        type: boolean
        required: false
        default: false
        description: Upload wire generated code

    outputs:
      component:
        value: ${{ jobs.version.outputs.component }}
        description: Extracted component

      version:
        value: ${{ jobs.version.outputs.version }}
        description: Extracted version

jobs:
  version:
    name: Version
    if: inputs.only-dependencies != false
    uses: webitel/reusable-workflows/.github/workflows/_version.yml@main
    with:
      development-branch: ${{ inputs.development-branch }}
      triggered-branch: ${{ inputs.triggered-branch }}
      build-number: ${{ inputs.build-number }}

  dependencies:
    name: Dependencies
    runs-on: [ arc-runner-set ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download dependencies
        run: go mod download

  generated:
    name: Code
    runs-on: [ arc-runner-set ]
    if: inputs.generate-code == true
    steps:
      - name: Generate code
        run: go generate ./...

      - name: Upload Go generated code
        uses: actions/upload-artifact@v4
        with:
          name: generated-code-go
          compression-level: 9
          path: gen/go

      - name: Upload wire generated code
        if: inputs.wire == true
        uses: actions/upload-artifact@v4
        with:
          name: generated-code-wire
          compression-level: 9
          path: cmd/wire_gen.go