name: Prepare

on:
  workflow_call:
    inputs:
      development-branch:
        type: string
        required: false
        default: main
        description: Name of the development branch

      triggered-branch:
        type: string
        required: false
        default: ${{ github.ref_name }}
        description: Name of the triggered branch

      only-dependencies:
        type: string
        required: false
        default: false

      generated-code-path:
        type: string
        required: false
        default: ''

      arch:
        type: string
        required: false
        default: amd64
        description: Comma-separated list of target architectures (e.g., "amd64" or "amd64, arm64").

      codename:
        type: string
        required: false
        default: bookworm
        description: Comma-separated list of Debian codenames (e.g., "bookworm" or "bookworm, jammy").

    outputs:
      version:
        value: ${{ jobs.version.outputs.version }}
        description: Extracted version

      arch-matrix:
        value: ${{ jobs.version.outputs.arch-matrix }}
        description: JSON array of target architectures

      codename-matrix:
        value: ${{ jobs.version.outputs.codename-matrix }}
        description: JSON array of Debian codenames

jobs:
  version:
    name: Version
    if: inputs.only-dependencies != 'true'
    uses: webitel/reusable-workflows/.github/workflows/_version.yml@v1
    with:
      development-branch: ${{ inputs.development-branch }}
      triggered-branch: ${{ inputs.triggered-branch }}
      arch: ${{ inputs.arch }}
      codename: ${{ inputs.codename }}

  dependencies:
    name: Dependencies
    runs-on: [ arc-backend-runner-set ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Download dependencies
        run: go mod download

  generated:
    name: Code
    runs-on: [ arc-backend-runner-set ]
    if: inputs.generated-code-path != ''
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Generate code
        run: go generate ./...

      - name: Upload generated code
        uses: actions/upload-artifact@v7
        with:
          name: generated-code
          retention-days: 1
          compression-level: 9
          path: |
            dummy-file-to-keep-directory-structure.txt
            ${{ inputs.generated-code-path }}
