name: Build

on:
  workflow_call:
    inputs:
      version:
        description: Extracted version to use for the build
        required: true
        type: string

      version-build:
        required: true
        type: string

      build-timestamp:
        required: true
        type: string
        description: UTC build timestamp in ISO-8601 format

      version-metadata:
        type: string
        required: false

      prerelease:
        type: string
        required: false

      package-name:
        type: string
        required: true

      package-description:
        type: string
        required: true

      app-root:
        type: string
        required: true
        description: Absolute target directory where built frontend assets will be installed

      package-contents:
        type: string
        required: true
        description: |
          Package contents specification in nFPM format.
          See: https://github.com/webitel/reusable-workflows/tree/main/actions/nfpm-build-action#contents-format

      package-depends:
        type: string
        required: false
        description: Package dependencies (comma-separated)

      package-conflicts:
        type: string
        required: false
        description: Packages this package conflicts with (comma-separated)

      package-replaces:
        type: string
        required: false
        description: Packages this package replaces (comma-separated)

      package-provides:
        type: string
        required: false
        description: Virtual or legacy packages this package provides (comma-separated)

      scripts:
        type: string
        required: false
        description: |
          Scripts to run at specific stages.
          Format:
            <stage>: <path-to-script>
          Example:
            postinstall: packaging/postinstall.sh
            preremove: packaging/preremove.sh

      arch:
        type: string
        required: false
        default: all
        description: Target architecture (e.g., all, amd64, arm64).

jobs:
  compile:
    name: Application
    runs-on: [ arc-frontend-runner-set ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install dependencies
        run: npm ci --install-links --install-strategy shallow

      - name: Build application
        env:
          VITE_BUILD_NUMBER: ${{ inputs.version-build }}
          VITE_BUILD_TIMESTAMP: ${{ inputs.build-timestamp }}

        run: npm run build

      - name: Parse package contents for upload
        id: parse-upload-pattern
        if: inputs.package-contents != ''
        uses: webitel/reusable-workflows/actions/parse-artifact-pattern@parse-artifact-pattern-v1.0.0
        with:
          parser: package-contents
          content: ${{ inputs.package-contents }}

      - name: Parse scripts for upload
        id: parse-scripts-pattern
        if: inputs.scripts != ''
        uses: webitel/reusable-workflows/actions/parse-artifact-pattern@parse-artifact-pattern-v1.0.0
        with:
          parser: scripts
          content: ${{ inputs.scripts }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build-source-${{ inputs.arch }}
          retention-days: 1
          compression-level: 9
          include-hidden-files: true
          path: |
            dist
            ${{ steps.parse-upload-pattern.outputs.upload-pattern }}
            ${{ steps.parse-scripts-pattern.outputs.upload-pattern }}

  build:
    name: Package
    needs: [ compile ]
    runs-on: [ arc-runner-set ]
    steps:
      - name: Download compiled file
        uses: actions/download-artifact@v8
        with:
          name: build-source-${{ inputs.arch }}
          path: build-source

      - name: Build package
        id: build
        uses: webitel/reusable-workflows/actions/nfpm-build@nfpm-build-v2
        with:
          formats: deb
          target: packages
          maintainer: Webitel <support@webitel.com>
          homepage: https://webitel.com
          arch: ${{ inputs.arch }}
          platform: linux
          package-name: ${{ inputs.package-name }}
          package-description: ${{ inputs.package-description }}
          version: ${{ inputs.version }}
          release: ${{ inputs.version-build }}
          prerelease: ${{ inputs.prerelease }}
          version-metadata: ${{ inputs.version-metadata }}
          contents: |
            src=build-source dst=${{ inputs.app-root }} type=tree
            ${{ inputs.package-contents }}

          scripts: ${{ inputs.scripts }}
          depends: ${{ inputs.package-depends }}
          conflicts: ${{ inputs.package-conflicts }}
          replaces: ${{ inputs.package-replaces }}
          provides: ${{ inputs.package-provides }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build-packages-${{ inputs.arch }}
          retention-days: 7
          compression-level: 9
          path: packages
