name: Prepare

on:
  workflow_call:
    inputs:
      development-branch:
        type: string
        required: false
        default: main
        description: Name of the development branch

      triggered-branch:
        type: string
        required: false
        default: ${{ github.ref_name }}
        description: Name of the triggered branch

      only-dependencies:
        type: string
        required: false
        default: false

    outputs:
      version:
        value: ${{ jobs.version.outputs.version }}
        description: Extracted version

jobs:
  version:
    name: Version
    uses: webitel/reusable-workflows/.github/workflows/_version.yml@9597f2c85d2d5942120c204709f5abf239372624
    if: inputs.only-dependencies != 'true'
    with:
      development-branch: ${{ inputs.development-branch }}
      triggered-branch: ${{ inputs.triggered-branch }}

  dependencies:
    name: Dependencies
    runs-on: [ arc-frontend-runner-set ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Download dependencies
        run: npm ci --install-links --install-strategy shallow
